TaskManager/Models/Contact.cs
namespace TaskManager.Models
{
    public class Contact
    {
        public int Id { get; set; }
        public ContactType Type { get; set; }
        public string Value { get; set; }
        public virtual Person Person { get; set; }
    }

    public enum ContactType
    {
        Phone,
        Email,
        Skype,
        Other
    }
}

TaskManager/Models/Person.cs
using System;
using System.Linq;

namespace TaskManager.Models
{
    public class Person
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public DateTime Birthday { get; set; }
        public string Organization { get; set; }
        public string Position { get; set; }
        public IQueryable<Contact> Contacts { get; set; }

        public DTO.Person ToDto()
        {
            return new DTO.Person(this);
        }
    }
}

TaskManager/Models/Record.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TaskManager.Models
{
    public class Record
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public RecordType Type { get; set; }

        [Required]
        public string Subject { get; set; }

        [Required]
        public DateTime StartTime { get; set; }

        [Required]
        public DateTime EndTime { get; set; }

        public string  Place { get; set; }

        public DTO.Record ToDto()
        {
            return new DTO.Record(this);
        }
    }

    public enum RecordType
    {
        Meeting,
        Task,
        Note
    }
}

TaskManager/Models/RecordsContext.cs
using System;
using System.Data.Entity;

namespace TaskManager.Models
{
    public class RecordsContext : DbContext
    {
        public RecordsContext() : base("name=RecordsContext")
        {
            InitializeContext();
        }

        public RecordsContext(string connectionString) : base(connectionString)
        {
            InitializeContext();
        }

        private static void InitializeContext()
        {
            AppDomain.CurrentDomain.SetData("DataDirectory", System.IO.Directory.GetCurrentDirectory());
            // Database.SetInitializer<RecordsContext>(new CreateDatabaseIfNotExists<RecordsContext>());
        }
        
        public DbSet<Record> Records { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Person> Persons { get; set; }
    }
}

TaskManager/Controllers/ContactsController.cs
using System.Linq;
using System.Web.Mvc;
using TaskManager.Models;

namespace TaskManager.Controllers
{
    public class ContactsController : Controller
    {
        RecordsContext _db = new RecordsContext();

        public ActionResult Index()
        {
            return View();
        }
    }
}

TaskManager/Controllers/RecordsController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using TaskManager.Exceptions;
using TaskManager.Models;

namespace TaskManager.Controllers
{
    public class RecordsController : Controller
    {
        private RecordsContext _db = new RecordsContext();

        public RecordsController()
        {
        }

        public ActionResult Index()
        {
            var records = _db.Records.ToList().Select(x => x.ToDto()).ToList();
            return View(records);
        }
        
        public ActionResult Schedule()
        {
            var records = _db.Records.ToList().Select(x => x.ToDto()).ToList();
            return View(records);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(DTO.Record record)
        {
            try
            {
                var newRecord = _db.Records.Create();
                
                newRecord.Subject = record.Subject;
                DateTime result;
                if (DateTime.TryParseExact(record.StartTime, "yyyy/MM/dd HH:mm", new DateTimeFormatInfo(),
                    DateTimeStyles.None, out result))
                {
                    newRecord.StartTime = result;
                }
                else
                {
                    throw new RecordCreateFailedException("Дата не заполнена или имеет не верный формат");
                }

                if (DateTime.TryParseExact(record.EndTime, "yyyy/MM/dd HH:mm", new DateTimeFormatInfo(),
                    DateTimeStyles.None, out result))
                {
                    newRecord.EndTime = result;
                }
                else
                {
                    throw new RecordCreateFailedException("Дата не заполнена или имеет не верный формат");
                }

                RecordType type;
                if (Enum.TryParse(record.Type, true, out type))
                {
                    newRecord.Type = type;
                }
                else
                {
                    throw new RecordCreateFailedException("Тип записи не заполнен или имеет не верный формат");
                }

                _db.Records.Add(newRecord);

                _db.SaveChanges();
            }
            catch (Exception e)
            {
                ViewBag.Error = "Не удалось создать новую запись.";
                return View();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var record = _db.Records.Find(id).ToDto();

            if (record == null)
            {
                return HttpNotFound();
            }

            return View(record);
        }
        
        [HttpPost]
        public ActionResult Edit(DTO.Record record)
        {
            try
            {
                var updateableRecord = _db.Records.Find(record.Id);

                if (updateableRecord == null)
                {
                    return HttpNotFound();
                }

                updateableRecord.Subject = record.Subject;
                DateTime result;
                if (DateTime.TryParseExact(record.StartTime, "yyyy/MM/dd HH:mm", new DateTimeFormatInfo(),
                    DateTimeStyles.None, out result))
                {
                    updateableRecord.StartTime = result;
                }
                else
                {
                    throw new RecordUpdateFailedExceprtion("Дата не заполнена или имеет не верный формат");
                }

                if (DateTime.TryParseExact(record.EndTime, "yyyy/MM/dd HH:mm", new DateTimeFormatInfo(),
                    DateTimeStyles.None, out result))
                {
                    updateableRecord.EndTime = result;
                }
                else
                {
                    throw new RecordUpdateFailedExceprtion("Дата не заполнена или имеет не верный формат");
                }

                RecordType type;
                if (Enum.TryParse(record.Type, true, out type))
                {
                    updateableRecord.Type = type;
                }
                else
                {
                    throw new RecordUpdateFailedExceprtion("Тип записи не заполнен или имеет не верный формат");
                }
                
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ViewBag.Error = "Обновление прощло с ошибкой";
                return View(record);
            }
        }
    }
}

TaskManager/Views/Contacts/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Under construction</h2>
<p>Section will be available as soon as possible.</p>

TaskManager/Views/Records/Create.cshtml
@model TaskManager.DTO.Record

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.Error != null)
{
    <span style="color: red;">@ViewBag.Error</span>
}

@using (Html.BeginForm("Create", "Records"))
{
    <div class="form-group">
        <label for="subject">Тема</label>
        <input class="form-control" id="subject" name="Subject" />
    </div>

    <div class="form-group">
        <label for="starttime">Начало</label>
        <input class="form-control" id="starttime" name="StartTime" />
    </div>

    <div class="form-group">
        <label for="endtime">Конец</label>
        <input class="form-control" id="endtime" name="EndTime" />
    </div>

    <div class="form-group">
        <label for="type">Тип</label>
        <select class="form-control" id="type" name="Type">
            <option>Meeting</option>
            <option>Task</option>
            <option>Note</option>
        </select>
    </div>

    <input type="submit" value="Create" class="btn btn-default"/>
}

<script>
    $(document).ready(function () {
        $('#starttime, #endtime').datetimepicker();
    });
</script>

TaskManager/Views/Records/Edit.cshtml
@model TaskManager.DTO.Record

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.Error != null)
{
    <span style="color: red;">@ViewBag.Error</span>
}

@using (Html.BeginForm("Edit", "Records"))
{
    <input type="hidden" value="@Model.Id" name="Id"/>
    <div class="form-group">
        <label for="subject">Тема</label>
        <input class="form-control" id="subject" name="Subject" value="@Model.Subject"/>
    </div>

    <div class="form-group">
        <label for="starttime">Начало</label>
        <input class="form-control" id="starttime" name="StartTime" value="@Model.StartTime" />
    </div>

    <div class="form-group">
        <label for="endtime">Конец</label>
        <input class="form-control" id="endtime" name="EndTime" value="@Model.EndTime" />
    </div>

    <div class="form-group">
        <label for="type">Тип</label>
        <select class="form-control" id="type" name="Type">
            <option @(Model.Type == "Meeting" ? "selected=selected" : "")>Meeting</option>
            <option @(Model.Type == "Task" ? "selected=selected" : "")>Task</option>
            <option @(Model.Type == "Note" ? "selected=selected" : "")>Note</option>
        </select>
    </div>

    <input type="submit" value="Update" class="btn btn-default" />
}

<script>
    $(document).ready(function () {
        $('#starttime, #endtime').datetimepicker();

        $('#starttime').datetimepicker({
            value: moment('@Model.StartTime').format('Y/MM/DD HH:mm')
        });

        $('#endtime').datetimepicker({
            value: moment('@Model.EndTime').format('Y/MM/DD HH:mm')
        });
    });
</script>

TaskManager/Views/Records/Index.cshtml
@model  List<TaskManager.DTO.Record>

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/ecmascript" src="../../Scripts/jquery.min.js"></script>
<script type="text/ecmascript" src="../../Scripts/grid.locale-en.js"></script>
<script type="text/ecmascript" src="../../Scripts/jquery.jqGrid.min.js"></script>
<link rel="stylesheet" type="text/css" media="screen" href="../../Content/jquery-ui.css" />
<link rel="stylesheet" type="text/css" media="screen" href="../../Content/ui.jqgrid.css" />
<meta charset="utf-8" />

<table id="jqGrid"></table>
<div id="jqGridPager"></div>

<script type="text/javascript">

    $(document).ready(function () {
        var lastSel;

        $("#jqGrid").jqGrid({
            datatype: "local",
            height: 250,
            colNames: ['Id', 'Subject', 'Type', 'Start Time', 'End Time'],
            colModel: [
                { name: 'Id', index: 'Id', width: 60, sorttype: "int" },
                { name: 'Subject', index: 'Subject', width: 90, sorttype: "string" },
                { name: 'Type', index: 'Type', width: 100 },
                { name: 'StartTime', index: 'Start Time', width: 80, align: "right", sorttype: "date" },
                { name: 'EndTime', index: 'End Time', width: 80, align: "right", sorttype: "date" }
            ],
            multiselect: true,
            caption: "Task List",
            onSelectRow: function(id){
                //if(id && id!==lastSel){
                //    $(this).restoreRow(lastSel);
                //    lastSel=id;
                //}
                window.open('/Records/Edit?id=' + id, '_blank');
                //jQuery(this).editRow(id, true);
            }
        });

        var mydata = @Html.Raw(Json.Encode(Model));

        for (var i = 0; i < mydata.length; i++)
            $("#jqGrid").jqGrid('addRowData', i + 1, Object.assign({}, mydata[i], { StartTime: new Date(mydata[i].StartTime), EndTime: new Date(mydata[i].EndTime) }));

        $('#jqGrid').filterToolbar();
    });
</script>

TaskManager/Views/Records/Schedule.cshtml
@model System.Collections.Generic.List<TaskManager.DTO.Record>

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="calendar"></div>
<script>
    $(document).ready(function () {
        var mydata = @Html.Raw(Json.Encode(Model));

        $('#calendar').fullCalendar({
            header: {
                left: 'today prev,next',
                center: 'title',
                right: 'agendaDay,agendaWeek,month'
            },
            scrollTime: '00:00',
            events: mydata.map(x => {
                return { title: x.Subject, start: x.StartTime, end: x.EndTime }
            }),
            defaultView: 'agendaDay'
        });
    });
</script>

TaskManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Task Manager</title>
    @Styles.Render("~/Content/css")

    <script type="text/ecmascript" src="../../Scripts/jquery.min.js"></script>
    <script type="text/ecmascript" src="../../Scripts/grid.locale-en.js"></script>
    <script type="text/ecmascript" src="../../Scripts/jquery.jqGrid.min.js"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="../../Content/jquery-ui.css">
    <link rel="stylesheet" type="text/css" media="screen" href="../../Content/ui.jqgrid.css">
    <link rel="stylesheet" href="../../Content/scheduler.min.css"/>
    <link rel="stylesheet" href="../../Content/jquery.datetimepicker.css"/>
    <link rel="stylesheet" href="../../Content/fullcalendar.css"/>

    <script src="../../Scripts/moment.min.js"></script>
    <script src="../../Scripts/fullcalendar.min.js"></script>
    <script src="../../Scripts/scheduler.min.js"></script>

    <script src="../../Scripts/jquery.datetimepicker.js"></script>
    <meta charset="utf-8">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Task Manager", "Index", "Records", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Все записи", "Index", "Records")</li>
                    <li>@Html.ActionLink("Расписание", "Schedule", "Records")</li>
                    <li>@Html.ActionLink("Создать запись", "Create", "Records")</li>
                    <li>@Html.ActionLink("Контакты", "Index", "Contacts")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>